source "https://rubygems.org"

ruby "2.1.0"

gem "committee"
gem "excon"
gem "multi_json"
gem "oj"
gem "puma"
gem "rack"
gem "rack-instruments"
gem "rack-cache"
gem "sass"
gem "sinatra", require: "sinatra/base"
gem "sinatra-router"
gem "slim"
gem "sprockets"
gem "uglifier"
gem "yui-compressor"
